### PR TITLE
adjusted CSS and JS after being able to see generated files

### PR DESCRIPTION
**Pull request by StommePoes**
CSS: removed focus outlines on normally-non-focusables we are focussing on so the Next-Tab works for users as expected.

JS: force smoothscroll destinations to receive focus.

root.tt: negative tabindex added to nav; footer got its ID back

events.haml: no idea, I think it's just merged new stuff from main repo.

### CODE REVIEW

**Comment by Sweet-kid** [comment]
Hi @StommePoes :)

Why have you edited events.haml? That file contains HAML for all the events (new & old), which generates events.tt when render_events.pl is run.
Whenever there is a new event, we add it in "Upcoming events" & move all old events to "Previous events". You have added the "Upcoming event" several times which I have not understood.

Thanks.

**Comment by StommePoes** [comment]
@sweet-kid I didn't add it, I have no idea where that comes from! I even pulled from the main fork again and merged. I definitely didn't write it! So you are free to destroy it. 

I didn't add any upcoming events, but it's a change from my previous git state, so I just pushed it.

**Comment by Sweet-kid** [comment]
@StommePoes Ok, I will take a deeper look over the weekend (if no one does that in the mean time :).
Thanks :)

**Comment by xsawyerx** [comment]
When you generate the website, it uses the new event template and updates the events Haml file with it. That's why it happened.

@StommePoes Thanks a ton for the work! :)

**Comment by StommePoes** [comment]
whups. So, someone check that on some non-Windows phone browsers...

**Pull request merged**
